### PR TITLE
Use the image's original filename when caching on disk.

### LINKED ISSUE #904: Import fails when image doesn't have extension
This regression was caused by https://github.com/GoogleCloudPlatform/compute-image-tools/commit/7f5fa326489b2d459dc939fbfffb68e11b01c538.

Here's a repro:

```bash
% daisy -var:source_disk_file=gs://edens-images/image \
        -var:image_name=imagenoext -zone=us-central1-a \
        -project=edens-test daisy_workflows/image_import/import_image.wf.json
[import-image]: 2019-08-28T07:22:28-07:00 Error running workflow: step "import-disk" run error: step "wait-for-signal" run error: WaitForInstancesSignal FailureMatch found for "inst-importer-import-image-import-disk-jmj9x": "ImportFailed: Failed to convert source to raw. [Privacy-> error:     (0.00/100%)#015qemu-img: Could not open '\\''/daisy-scratch/image.gs://edens-images/image'\\'': Could not open '\\''/daisy-scratch/image.gs://edens-images/image'\\'': No such file or directory <-Privacy]'"
[import-image]: 2019-08-28T07:22:28-07:00 Workflow "import-image" cleaning up (this may take up to 2 minutes).
```

### PR DESCRIPTION
**Pull request by EricEdens**
Fixes #904.

Three changes:
 1. Use the image's original filename.
 2. Use Bash's regex operator (`=~`) to determine whether the image is an `ova`.
 2. Added two tests to confirm this behavior.

### CODE REVIEW

File: daisy_workflows/image_import/import_image.sh [hunk 1]
```diff
@@ -56,7 +54,7 @@ function copyImageToScratchDisk() {
   local scratchDiskSizeGigabytes=$(awk "BEGIN {print int(((${SOURCE_SIZE_BYTES} - 1)/${BYTES_1GB}) + 1)}")
   # We allocate double capacity for OVA, which would
   # require making an additional copy of its enclosed VMDK.
-  if [[ "${SOURCE_FILE_EXT}" == "ova" ]]; then
+  if [[ "${IMAGE_PATH}" =~ \.[oO][vV][aA]$ ]]; then
```
Comment (zoran15) [inline daisy_workflows/image_import/import_image.sh]: Something like: \.(?i)(ova)(?-i)$ would be more readable

Below as well
